#!/bin/bash -e
cur_path=$(pwd)

export PATH=$(pwd):$PATH

prepare_build_env() {
  echo "Prepare build environment for Android"
  sudo apt-get update
  sudo apt-get install openjdk-8-jdk
  sudo apt-get update
  sudo apt-get -f install
  sudo apt-get install git-core gnupg flex bison gperf build-essential zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z-dev ccache libgl1-mesa-dev libxml2-utils xsltproc unzip
}

get_aosp() {
  cd $cur_path

  echo "Get latest AOSP from Tsinghua mirror"
  if [ ! -d .repo ]
  then
    repo init -u https://aosp.tuna.tsinghua.edu.cn/platform/manifest
  fi

  repo sync -j4
}

get_kernel() {
  cd $cur_path/kernel
  echo "Get HiKey Kernel"
  git clone https://aosp.tuna.tsinghua.edu.cn/kernel/hikey-linaro.git
}

build_aosp() {
  echo "Build AOSP using HiKey variant"
}

main() {
  case $1 in
    "prepare")
      prepare_build_env
      ;;
    "sync")
      get_aosp
      get_kernel
      ;;
    "build")
      build_aosp
      ;;
    "all")
      prepare_build_end
      get_aosp
      build_aosp
      ;;
  esac
}

main $1
